// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoxzqrgpzr41mmAOyuSunymS843yzYSkY',
    appId: '1:819080045581:web:fdb69c2a3bf670ca282144',
    messagingSenderId: '819080045581',
    projectId: 'ebazar-2026',
    authDomain: 'ebazar-2026.firebaseapp.com',
    storageBucket: 'ebazar-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAJ5_GErwguhRCHSvJT95rFBx4zUwiGFI',
    appId: '1:819080045581:android:ab56d240b0a0c679282144',
    messagingSenderId: '819080045581',
    projectId: 'ebazar-2026',
    storageBucket: 'ebazar-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz5WLqiPjOGoASNMk25M-bIgH9d7iMebs',
    appId: '1:819080045581:ios:c96a1f2c31fd86e5282144',
    messagingSenderId: '819080045581',
    projectId: 'ebazar-2026',
    storageBucket: 'ebazar-2026.firebasestorage.app',
    iosBundleId: 'com.ebazarz.murad.ebazarx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz5WLqiPjOGoASNMk25M-bIgH9d7iMebs',
    appId: '1:819080045581:ios:c96a1f2c31fd86e5282144',
    messagingSenderId: '819080045581',
    projectId: 'ebazar-2026',
    storageBucket: 'ebazar-2026.firebasestorage.app',
    iosBundleId: 'com.ebazarz.murad.ebazarx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoxzqrgpzr41mmAOyuSunymS843yzYSkY',
    appId: '1:819080045581:web:884556a1b479f3e9282144',
    messagingSenderId: '819080045581',
    projectId: 'ebazar-2026',
    authDomain: 'ebazar-2026.firebaseapp.com',
    storageBucket: 'ebazar-2026.firebasestorage.app',
  );
}
